# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties on https://modmuss50.me/fabric.html
minecraft_version=26.3
loom_version=1.18-SNAPSHOT
loader_version=0.19.5
fabric_api_version=0.161.0+26.3

# Mod Properties
mod_version=2.0.29
maven_group=dev.amymialee
mod_id=visiblebarriers

# Publishing
curseforge_id = 507228
curseforge_slug = visiblebarriers
modrinth_id = ajdfGxGU
modrinth_slug = visiblebarriers
minecraft_version_range_start=26.3
minecraft_version_range_end=26.3

# Dependencies
# Polymer from https://modrinth.com/mod/polymer/versions
polymer_version=0.18.2+26.3
# Mod Menu from https://modrinth.com/mod/modmenu/versions
modmenu_version=21.0.0-beta.1
# Datasync from https://maven.uuid.gg/#/releases/dev/upcraft/datasync
datasync_version=datasync-minecraft-26.1-fabric:0.11.0
# Midnightlib from https://www.midnightdust.eu/wiki/midnightlib/
midnightlib_version = 1.9.3+26.3-fabric