# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties on https://modmuss50.me/fabric.html
minecraft_version=26.3
loader_version=0.19.5

# Mod Properties
mod_version=2.0.27
maven_group=amymialee
archives_base_name=visiblebarriers

# Publishing
curseforge_id = 507228
curseforge_slug = visiblebarriers
modrinth_id = ajdfGxGU
modrinth_slug = visiblebarriers
minecraft_version_range_start=26.3
minecraft_version_range_end=26.3

# Dependencies
fabric_version=0.161.0+26.3
polymer_version=0.18.2+26.3